export default [
  {
    id: 1,
    name: "Aino Virtanen",
    title: "HR Manager",
    salary: 4200,
    phone: "040-1234567",
    email: "aino.virtanen@example.com",
    animal: "Owl",
    startDate: "2018-04-01",
    location: "Helsinki",
    department: "Human Resources",
    skills: ["Recruiting", "Communication", "Employee Relations"],
  },
  {
    id: 2,
    name: "Mikko Laine",
    title: "Software Engineer",
    salary: 5100,
    phone: "050-7891234",
    email: "mikko.laine@example.com",
    animal: "Fox",
    startDate: "2020-09-15",
    location: "Espoo",
    department: "IT",
    skills: ["JavaScript", "React", "Node.js"],
  },
  {
    id: 3,
    name: "Sara Korhonen",
    title: "UX Designer",
    salary: 4600,
    phone: "045-2348765",
    email: "sara.korhonen@example.com",
    animal: "Cat",
    startDate: "2019-06-10",
    location: "Tampere",
    department: "Design",
    skills: ["UI Design", "Prototyping", "User Research"],
  },
  {
    id: 4,
    name: "Lauri Niemi",
    title: "Marketing Specialist",
    salary: 3800,
    phone: "041-6549873",
    email: "lauri.niemi@example.com",
    animal: "Raven",
    startDate: "2021-02-01",
    location: "Turku",
    department: "Marketing",
    skills: ["SEO", "Social Media", "Copywriting"],
  },
  {
    id: 5,
    name: "Emilia Heikkinen",
    title: "Data Analyst",
    salary: 4900,
    phone: "044-1122334",
    email: "emilia.heikkinen@example.com",
    animal: "Otter",
    startDate: "2022-01-20",
    location: "Oulu",
    department: "Data & Analytics",
    skills: ["Python", "SQL", "Data Visualization"],
  },
  {
    id: 6,
    name: "Aleksi Mäkinen",
    title: "Systems Administrator",
    salary: 4700,
    phone: "046-2233445",
    email: "aleksi.makinen@example.com",
    animal: "Wolf",
    startDate: "2017-11-11",
    location: "Espoo",
    department: "IT",
    skills: ["Linux", "Networking", "Security"],
  },
  {
    id: 7,
    name: "Noora Salonen",
    title: "Project Manager",
    salary: 5500,
    phone: "050-9988776",
    email: "noora.salonen@example.com",
    animal: "Hedgehog",
    startDate: "2016-05-05",
    location: "Helsinki",
    department: "Operations",
    skills: ["Leadership", "Budgeting", "Agile Management"],
  },
  {
    id: 8,
    name: "Eero Koskinen",
    title: "Financial Analyst",
    salary: 4800,
    phone: "043-5566778",
    email: "eero.koskinen@example.com",
    animal: "Falcon",
    startDate: "2019-12-09",
    location: "Tampere",
    department: "Finance",
    skills: ["Accounting", "Excel", "Forecasting"],
  },
  {
    id: 9,
    name: "Jenna Rantanen",
    title: "Front-End Developer",
    salary: 5000,
    phone: "045-6677889",
    email: "jenna.rantanen@example.com",
    animal: "Deer",
    startDate: "2020-07-13",
    location: "Lahti",
    department: "IT",
    skills: ["HTML", "CSS", "Vue.js"],
  },
  {
    id: 10,
    name: "Oskari Peltonen",
    title: "Customer Support Lead",
    salary: 3900,
    phone: "040-3344556",
    email: "oskari.peltonen@example.com",
    animal: "Dog",
    startDate: "2018-03-22",
    location: "Helsinki",
    department: "Customer Service",
    skills: ["Problem Solving", "CRM Systems", "Communication"],
  },
  {
    id: 11,
    name: "Veera Lehtonen",
    title: "Content Strategist",
    salary: 4300,
    phone: "050-2233445",
    email: "veera.lehtonen@example.com",
    animal: "Swan",
    startDate: "2021-08-16",
    location: "Kuopio",
    department: "Marketing",
    skills: ["Content Planning", "Storytelling", "SEO Writing"],
  },
  {
    id: 12,
    name: "Topias Rautiainen",
    title: "Cybersecurity Specialist",
    salary: 6100,
    phone: "045-7788990",
    email: "topias.rautiainen@example.com",
    animal: "Falcon",
    startDate: "2017-02-03",
    location: "Espoo",
    department: "IT Security",
    skills: ["Penetration Testing", "Firewalls", "Incident Response"],
  },
];
